name: Deploy to IIS Server

on:
  push:
    branches:
      - master
    paths:
      - "*.html"  # Sadece .html dosyalarındaki değişikliklerde tetiklenecek

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted runner üzerinde çalışacak

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Repository'yi self-hosted runner'a çekiyoruz

      - name: Copy files to IIS server
        run: Copy-Item -Path "C:\actions-runner\my_work\Self-Hosted-IIS\Self-Hosted-IIS\welcome.html" -Destination "C:\inetpub\wwwroot\welcome.html" -Force
