name: Deploy to IIS Server

on:
  push:
    branches:
      - master
    paths:
      - "*.html"  # Sadece .html dosyalarındaki değişikliklerde çalışır

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted runner üzerinde çalışacak

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Repository'yi çekiyoruz

      - name: Copy files to IIS server
        run: Copy-Item -Path "$env:GITHUB_WORKSPACE\welcome.html" -Destination "C:\inetpub\wwwroot\welcome.html" -Force
